"""
STEP 3 — reporter.py
Turns the organizer's result dict into a timestamped HTML report
(+ a plain-text summary) saved in the reports/ folder.
"""

import os
from datetime import datetime
from pathlib import Path


class Reporter:
    """Generate HTML + TXT reports from an organizer result dict."""

    def __init__(self, report_folder: str = "./reports"):
        self.report_folder = Path(report_folder)
        self.report_folder.mkdir(parents=True, exist_ok=True)

    # ── Helpers ────────────────────────────────────────────────────────────────

    @staticmethod
    def _total_files(summary: dict) -> int:
        return sum(len(v) for v in summary.values())

    @staticmethod
    def _total_size(summary: dict) -> int:
        return sum(
            f["size_bytes"]
            for files in summary.values()
            for f in files
        )

    @staticmethod
    def _human_size(num_bytes: int) -> str:
        for unit in ("B", "KB", "MB", "GB"):
            if num_bytes < 1024:
                return f"{num_bytes:.1f} {unit}"
            num_bytes /= 1024
        return f"{num_bytes:.1f} TB"

    # ── Public API ─────────────────────────────────────────────────────────────

    def generate(self, result: dict) -> dict:
        """
        Create both an HTML and a TXT report.

        Returns:
            {"html": <path>, "txt": <path>}
        """
        timestamp   = datetime.now().strftime("%Y%m%d_%H%M%S")
        html_path   = self.report_folder / f"report_{timestamp}.html"
        txt_path    = self.report_folder / f"report_{timestamp}.txt"

        html_path.write_text(self._build_html(result), encoding="utf-8")
        txt_path.write_text(self._build_txt(result),  encoding="utf-8")

        return {"html": str(html_path), "txt": str(txt_path)}

    # ── HTML builder ───────────────────────────────────────────────────────────

    def _build_html(self, result: dict) -> str:
        summary   = result["summary"]
        errors    = result["errors"]
        total     = self._total_files(summary)
        size_str  = self._human_size(self._total_size(summary))
        generated = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Category rows
        rows = ""
        for category, files in summary.items():
            if not files:
                continue
            exts = ", ".join(sorted({f["extension"] for f in files})) or "—"
            rows += f"""
            <tr>
                <td><strong>{category}</strong></td>
                <td style="text-align:center">{len(files)}</td>
                <td>{exts}</td>
            </tr>"""

        # Error rows
        err_section = ""
        if errors:
            err_rows = "".join(
                f"<tr><td>{e['file']}</td><td>{e['error']}</td></tr>"
                for e in errors
            )
            err_section = f"""
            <h2 style="color:#e74c3c">⚠ Errors ({len(errors)})</h2>
            <table>
              <tr><th>File</th><th>Error</th></tr>
              {err_rows}
            </table>"""

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Organizer Report — {generated}</title>
  <style>
    body  {{ font-family: Segoe UI, Arial, sans-serif; margin: 40px; background:#f9f9f9; color:#333 }}
    h1    {{ color:#2c3e50 }}
    h2    {{ color:#2980b9; margin-top:30px }}
    table {{ border-collapse:collapse; width:100%; background:#fff; margin-top:10px }}
    th,td {{ border:1px solid #ddd; padding:10px 14px; font-size:14px }}
    th    {{ background:#2980b9; color:#fff; text-align:left }}
    tr:nth-child(even) {{ background:#f2f2f2 }}
    .stat {{ display:inline-block; background:#2980b9; color:#fff;
             border-radius:8px; padding:12px 24px; margin:6px; font-size:18px }}
    .stat span {{ display:block; font-size:12px; opacity:.8 }}
  </style>
</head>
<body>
  <h1>📁 File Organizer Report</h1>
  <p>Generated: <strong>{generated}</strong> &nbsp;|&nbsp;
     Source: <code>{result.get('source','—')}</code> &nbsp;→&nbsp;
     Destination: <code>{result.get('destination','—')}</code></p>

  <div>
    <div class="stat">{total}<span>Files Moved</span></div>
    <div class="stat">{size_str}<span>Total Size</span></div>
    <div class="stat">{len(errors)}<span>Errors</span></div>
  </div>

  <h2>📊 Breakdown by Category</h2>
  <table>
    <tr><th>Category</th><th>Count</th><th>Extensions</th></tr>
    {rows}
  </table>

  {err_section}

  <p style="margin-top:40px;font-size:12px;color:#999">
    Auto-generated by <em>AutoOrganizer</em> — Task 2 Automation Script
  </p>
</body>
</html>"""

    # ── Plain-text builder ─────────────────────────────────────────────────────

    def _build_txt(self, result: dict) -> str:
        summary  = result["summary"]
        errors   = result["errors"]
        total    = self._total_files(summary)
        size_str = self._human_size(self._total_size(summary))
        lines    = [
            "=" * 60,
            "  FILE ORGANIZER REPORT",
            f"  Generated : {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"  Source    : {result.get('source','—')}",
            f"  Dest      : {result.get('destination','—')}",
            "=" * 60,
            f"  Total files moved : {total}",
            f"  Total size        : {size_str}",
            f"  Errors            : {len(errors)}",
            "-" * 60,
        ]
        for category, files in summary.items():
            if files:
                lines.append(f"  {category:<15} {len(files):>4} file(s)")
        if errors:
            lines += ["", "ERRORS:"]
            for e in errors:
                lines.append(f"  {e['file']} → {e['error']}")
        lines.append("=" * 60)
        return "\n".join(lines)
